#!/bin/bash

# Function to execute the command and monitor CPU usage
execute() {
  local COMMAND=$1
  local LOGFILE=$2
  local CSVFILE=$3

  # Start the command in the background and save the PID
  $COMMAND > "$LOGFILE" 2>&1 &
  local PID=$!

  # Write the CSV header
  echo "Timestamp,PID,CPU_Total(%),MEM_Absolute(KB),MEM_Relative(%),$(seq 0 $(( $(nproc) - 1 )) | sed 's/^/CPU_Core_/' | paste -sd,)" > "$CSVFILE"

  # Function to collect CPU usage and write it to the CSV file
  monitor_cpu() {
    while kill -0 "$PID" 2>/dev/null; do
        # Get CPU usage for the PID
        CPU_STATS=$(top -b -n 1 -p "$PID" | awk 'NR==8')
        CPU_TOTAL=$(echo "$CPU_STATS" | awk '{print $9}')

        # Get memory usage for the PID (absolute and relative)
        MEM_ABS=$(echo "$CPU_STATS" | awk '{print $6}')  # Absolute memory usage (e.g., in KB)
        MEM_REL=$(echo "$CPU_STATS" | awk '{print $10}') # Relative memory usage (percentage)

        # Get per-core CPU usage
        CORE_STATS=$(mpstat -P ALL 1 1 | awk '/^[0-9]/ {print $3}')

        # Create a timestamp
        TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")

        # Write data to the CSV file
        echo -n "$TIMESTAMP,$PID,$CPU_TOTAL,$MEM_ABS,$MEM_REL," >> "$CSVFILE"
        echo "$CORE_STATS" | paste -sd, >> "$CSVFILE"

        # Wait 1 second before collecting the next data point
        sleep 1
    done
  }

  # Start monitoring
  monitor_cpu

  # Output a message when the process ends
  echo "Process with PID $PID has ended. CPU monitoring completed for $CSVFILE."
}

# Ensure required directories exist
mkdir -p ./results/mst/simulated
mkdir -p ./results/mst/precomputed
mkdir -p ./precomputed/mst
mkdir -p ./results/mst_smart_loop/simulated
mkdir -p ./results/mst_smart_loop/precomputed
mkdir -p ./precomputed/mst_smart_loop
mkdir -p ./results/nearest/simulated
mkdir -p ./results/nearest/precomputed
mkdir -p ./precomputed/nearest

# Simulated MST
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0250.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-0250.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/0250.log" "./results/mst/simulated/0250.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0500.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-0500.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/0500.log" "./results/mst/simulated/0500.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-1000.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-1000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/1000.log" "./results/mst/simulated/1000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-2000.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-2000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/2000.log" "./results/mst/simulated/2000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-3000.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-3000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/3000.log" "./results/mst/simulated/3000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-newest.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/newest.log" "./results/mst/simulated/newest.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-double.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-newest-double.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/newest-double.log" "./results/mst/simulated/newest-double.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-triple.yaml --islConfig ./resources/configs/islMstConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst/precomputed-newest-triple.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/simulated/newest-triple.log" "./results/mst/simulated/newest-triple.csv"

# Precomputed MST
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0250.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-0250.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/0250.log" "./results/mst/precomputed/0250.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0500.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-0500.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/0500.log" "./results/mst/precomputed/0500.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-1000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-1000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/1000.log" "./results/mst/precomputed/1000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-2000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-2000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/2000.log" "./results/mst/precomputed/2000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-3000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-3000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/3000.log" "./results/mst/precomputed/3000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-newest.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/newest.log" "./results/mst/precomputed/newest.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-double.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-newest-double.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/newest-double.log" "./results/mst/precomputed/newest-double.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-triple.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst/precomputed-newest-triple.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst/precomputed/newest-triple.log" "./results/mst/precomputed/newest-triple.csv"

# Simulated MST Smart Loop
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0250.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-0250.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/0250.log" "./results/mst_smart_loop/simulated/0250.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0500.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-0500.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/0500.log" "./results/mst_smart_loop/simulated/0500.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-1000.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-1000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/1000.log" "./results/mst_smart_loop/simulated/1000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-2000.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-2000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/2000.log" "./results/mst_smart_loop/simulated/2000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-3000.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-3000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/3000.log" "./results/mst_smart_loop/simulated/3000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-newest.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/newest.log" "./results/mst_smart_loop/simulated/newest.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-double.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-newest-double.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/newest-double.log" "./results/mst_smart_loop/simulated/newest-double.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-triple.yaml --islConfig ./resources/configs/islMstSmartLoopConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/mst_smart_loop/precomputed-newest-triple.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/simulated/newest-triple.log" "./results/mst_smart_loop/simulated/newest-triple.csv"

# Precomputed MST Smart Loop
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0250.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-0250.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/0250.log" "./results/mst_smart_loop/precomputed/0250.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0500.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-0500.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/0500.log" "./results/mst_smart_loop/precomputed/0500.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-1000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-1000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/1000.log" "./results/mst_smart_loop/precomputed/1000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-2000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-2000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/2000.log" "./results/mst_smart_loop/precomputed/2000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-3000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-3000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/3000.log" "./results/mst_smart_loop/precomputed/3000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-newest.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/newest.log" "./results/mst_smart_loop/precomputed/newest.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-double.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-newest-double.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/newest-double.log" "./results/mst_smart_loop/precomputed/newest-double.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-triple.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/mst_smart_loop/precomputed-newest-triple.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/mst_smart_loop/precomputed/newest-triple.log" "./results/mst_smart_loop/precomputed/newest-triple.csv"

# Simulated Nearest
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0250.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-0250.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/0250.log" "./results/nearest/simulated/0250.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0500.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-0500.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/0500.log" "./results/nearest/simulated/0500.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-1000.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-1000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/1000.log" "./results/nearest/simulated/1000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-2000.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-2000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/2000.log" "./results/nearest/simulated/2000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-3000.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-3000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/3000.log" "./results/nearest/simulated/3000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-newest.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/newest.log" "./results/nearest/simulated/newest.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-double.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-newest-double.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/newest-double.log" "./results/nearest/simulated/newest-double.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-triple.yaml --islConfig ./resources/configs/islNearestConfig.yaml --groundLinkConfig ./resources/configs/groundLinkNearestConfig.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateOutputFile ./precomputed/nearest/precomputed-newest-triple.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/simulated/newest-triple.log" "./results/nearest/simulated/newest-triple.csv"

# Precomputed Nearest
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0250.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-0250.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/0250.log" "./results/nearest/precomputed/0250.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-0500.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-0500.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/0500.log" "./results/nearest/precomputed/0500.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-1000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-1000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/1000.log" "./results/nearest/precomputed/1000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-2000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-2000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/2000.log" "./results/nearest/precomputed/2000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-3000.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-3000.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/3000.log" "./results/nearest/precomputed/3000.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-newest.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/newest.log" "./results/nearest/precomputed/newest.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-double.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-newest-double.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/newest-double.log" "./results/nearest/precomputed/newest-double.csv"
execute "./stardust --simulationConfig ./resources/configs/simulationManualConfig-newest-triple.yaml --computingConfig ./resources/configs/computingConfig.yaml --routerConfig ./resources/configs/routerAStarConfig.yaml --simulationStateInputFile ./precomputed/nearest/precomputed-newest-triple.gob --simulationPlugins DummyPlugin --statePlugins DummyPlugin" "./results/nearest/precomputed/newest-triple.log" "./results/nearest/precomputed/newest-triple.csv"
