SimulationConfiguration:
  StepInterval: 1
  StepMultiplier: 10
  SatelliteDataSource: starlink_500.tle
  SatelliteDataSourceType: tle
  UsePreRouteCalc: false
  MaxCpuCores: 30
  SimulationStartTime: "2025-01-01T00:00:00Z"
InterSatelliteLinkConfig:
  Neighbours: 4
  Protocol: pst_loop
RouterConfig:
  Protocol: a-star
ComputingConfiguration:
  - Cores: 512
    Memory: 4096
    Type: Edge
  - Cores: 1024
    Memory: 32768
    Type: Cloud
