SimulationConfiguration:
  StepInterval: -1
  StepMultiplier: 10
  SatelliteDataSource: starlink_newest.tle
  SatelliteDataSourceType: tle
  GroundStationDataSource: ground_stations.yml
  GroundStationDataSourceType: yml
  UsePreRouteCalc: false
  MaxCpuCores: 30
  SimulationStartTime: "2025-01-01T00:00:00Z"
InterSatelliteLinkConfig:
  Neighbours: 4
  Protocol: pst_loop
GroundLinkConfig:
  Protocol: nearest
RouterConfig:
  Protocol: a-star
ComputingConfiguration:
  - Cores: 0
    Memory: 0
    Type: None
  - Cores: 512
    Memory: 4096
    Type: Edge
  - Cores: 1024
    Memory: 32768
    Type: Cloud
